package main

var ( // 언어 변수
	// 영어
	langEN = `{
		"lang": "en",
		"keyEntryHolder": "https://www.twitch.tv/videos/000000000",
		"themeDark": "Dark",
		"themeLight": "Light",
		"statusDefault": "Status",
		"intervalCheck": "※ If you set it to 'Single Download', the download is relatively slow but very stable.\r\n※ Encoding proceeds according to the 'File -> Setting -> Encoding Type'.\r\nInterval Download is available in a single download.",
		"downloadOption": "Download Mode",
		"downloadOption1": "Multiple Download",
		"downloadOption2": "Single Download",
		"downloadOption3": "Recording",
		"codeFound": "Code found on clipboard.\r\nDo you want to use it?\r\n\r\nCode : ",
		"confirm": "Yes",
		"dismiss": "No",
		"ok": "Ok",
		"cancel": "Cancel",
		"runButton": "Download",
		"wrongLocation": "Location does not exist.\r\nLocation : ",
		"errRequireFile": "Please execute 'File -> Install Required Files' first.",
		"validateCode": "Validating code...",
		"invalidCode": "Invalid url.\r\nPlease check the url.",
		"waitForDownload": "Waiting for download...",
		"addQueue": "Adding queue. Please wait a moment.",
		"noQueue": "There are no VODs registered in the queue.",
		"downloading": "Downloading...",
		"waitIncompleteDownload": "Waiting for incomplete download...",
		"generateFile": "Generating file...",
		"merging": "Merging...",
		"encoding": "Encoding... This may take a long time.",
		"loadFile": "Loading file...",
		"downloadAndEncode": "Downloading & Encoding... This take a long time.",
		"recording": "Recording...",
		"downloadComplete": "Download Complete",
		"downloadSetting": "Download Setting",
		"saved": "Saved",
		"savedAndRunAgain": "Saved.",
		"optionLanguage": "Language",
		"optionDownload": "Download Mode",
		"optionMaxConnection": "Max Connection",
		"optionDownloadLocation": "Download Location",
		"optionEncoding": "Encoding",
		"optionEncodingType": "Encoding Type",
		"optionErrorHandle": "Display Error",
		"defaultSetting": "Default Setting",
		"downloadNecessary": "Downloading necessary file... This may take a long time.",
		"downloadNecessaryDone": "Program will restart after 5 seconds.",
		"menuFile": "File",
		"installRequireFile": "Install Required Files",
		"menuInfo": "Info",
		"menuInNotice": "Notice",
		"menuInLicense": "License",
		"menuMore": "More",
		"tabHome": "Home",
		"tabSetting": "Setting",
		"errorHTTP": "An unexpected error has occurred.\r\nProgram will be closed after 5 seconds.",
		"intervalDownload": "Interval Download",
		"errorLoadTime": "There is an error in the time format.\r\nEx) 02:11:23, 1:11:4, 0:2:4",
		"intervalStart": "Start",
		"intervalStop": "End",
		"intervalHour": "h",
		"intervalMin": "m",
		"intervalSec": "s",
		"fileNameSetting": "File Name",
		"loadProgram": "Preparing to start...",
		"foundNewVersion": "New Version",
		"askRunAgainLang": "If you change the language, you must restart the program.\r\nDo you want to restart the program?",
		"typeDirect": "Direct Input",
		"login": "Logging in...",
		"logout": "Logout",
		"waitLogin": "Waiting for login...",
		"hello": " Hello!",
		"chromeNotFound": "Must be installed Chrome or Chromium browser.",
		"highlightNotice": "Highlight video works only in single download.",
		"maxEntry": "Too long code.",
		"fileExplorer": "Open",
		"shouldSubmit": "Once you have changed the settings, you need to press the Save button to save.",
		"saveSetting": "Save",
		"editSettingNow": "Changing settings...",
		"exit": "Exit",
		"notSubscriber": "You are not a subscriber.\r\nWould you like to subscribe?",
		"unknownError": "Unknown Error",
		"setIntervalRange": "Setting vod range...",
		"addedQueue": "Added to queue.",
		"resetSetting": "Reset",
		"realResetSetting": "Are you sure you want to reset the settings?\r\nThe program restarts.",
		"vodTitle": "Title",
		"vodTime": "Duration",
		"vodStatus": "Status",
		"intervalRangeSaved": "Setting interval...",
		"alreadyAdded": "Already added video.",
		"stoppedDownload": "Progress has been canceled.",
		"stoppedNoStatus": "Can't' check the progress.",
		"canceled": "Canceled",
		"noFreeSpace": "Less than 10% of space left.",
		"errorHandleNoAlert": "Error page is disabled."
	}`

	// 한국어
	langKO = `{
		"lang": "ko",
		"keyEntryHolder": "https://www.twitch.tv/videos/000000000",
		"themeDark": "다크 모드",
		"themeLight": "라이트 모드",
		"statusDefault": "상태",
		"intervalCheck": "※ '단일 다운로드'로 설정할 경우 다운로드는 상대적으로 느리지만 매우 안정적입니다.\r\n※ '더보기 -> 설정 -> 인코딩 형식'으로 인코딩됩니다.\r\n구간 다운로드는 단일 다운로드에서 가능합니다.",
		"downloadOption": "다운로드 모드",
		"downloadOption1": "다중 다운로드",
		"downloadOption2": "단일 다운로드",
		"downloadOption3": "녹화",
		"codeFound": "클립보드에서 주소를 발견했습니다.\r\n사용하시겠습니까?\r\n\r\n",
		"confirm": "예",
		"dismiss": "아니요",
		"ok": "확인",
		"cancel": "취소",
		"runButton": "다운로드",
		"wrongLocation": "폴더가 존재하지 않습니다.\r\n위치 : ",
		"errRequireFile": "'더보기 -> 필수 파일 설치'을 실행해주세요.",
		"validateCode": "코드 검증 중...",
		"invalidCode": "잘못된 주소입니다.",
		"waitForDownload": "다운로드 대기 중...",
		"addQueue": "대기열 추가하는 중입니다. 잠시만 기다려주세요.",
		"noQueue": "대기열에 등록된 VOD가 없습니다.",
		"downloading": "다운로드 중...",
		"waitIncompleteDownload": "끝나지 않은 다운로드 대기 중...",
		"generateFile": "파일 생성하는 중...",
		"merging": "파일 병합하는 중...",
		"encoding": "인코딩 하는 중... 시간이 오래 걸릴 수 있습니다.",
		"loadFile": "파일 로딩 중...",
		"downloadAndEncode": "다운로드 & 인코딩 중... 시간이 오래 걸릴 수 있습니다.",
		"recording": "녹화 중...",
		"downloadComplete": "다운로드 완료",
		"downloadSetting": "다운로드 설정",
		"saved": "저장되었습니다.",
		"savedAndRunAgain": "저장되었습니다.",
		"optionLanguage": "언어",
		"optionDownload": "다운로드 모드",
		"optionMaxConnection": "최대 연결 개수",
		"optionDownloadLocation": "다운로드 위치",
		"optionEncoding": "인코딩",
		"optionEncodingType": "인코딩 형식",
		"optionErrorHandle": "오류 표시",
		"defaultSetting": "기본 설정",
		"downloadNecessary": "필요한 파일 다운로드 중... 시간이 오래 걸릴 수 있습니다.",
		"downloadNecessaryDone": "프로그램이 5초 후 재시작 됩니다.",
		"menuFile": "파일",
		"installRequireFile": "필수 파일 설치",
		"menuInfo": "정보",
		"menuInNotice": "공지사항",
		"menuInLicense": "라이센스",
		"menuMore": "더보기",
		"tabHome": "홈",
		"tabSetting": "설정",
		"errorHTTP": "예기치 못한 오류가 발생했습니다.\r\n프로그램이 5초 내로 종료됩니다.",
		"intervalDownload": "구간 다운로드",
		"errorLoadTime": "시간 형식에 오류가 있습니다.\r\n예) 02:11:23, 1:11:4, 0:2:4",
		"intervalStart": "시작",
		"intervalStop": "끝",
		"intervalHour": "시",
		"intervalMin": "분",
		"intervalSec": "초",
		"fileNameSetting": "파일 이름",
		"loadProgram": "  프로그램 로딩 중...",
		"foundNewVersion": "새로운 버전",
		"askRunAgainLang": "언어를 변경했으면 프로그램을 재시작 해야 합니다.\r\n재시작 하시겠습니까?",
		"typeDirect": "직접 입력",
		"login": "  로그인 하는 중...",
		"logout": "로그아웃",
		"waitLogin": "  로그인 기다리는 중...",
		"hello": "님 안녕하세요!",
		"chromeNotFound": "Chrome 또는 Chromium 브라우저가 설치되어 있어야 합니다.",
		"highlightNotice": "하이라이트 영상은 단일 다운로드만 가능합니다.",
		"maxEntry": "코드가 너무 깁니다.",
		"fileExplorer": "열기",
		"shouldSubmit": "설정을 변경했으면 저장을 눌러서 저장해야합니다.",
		"saveSetting": "저장",
		"editSettingNow": "설정 변경 중...",
		"exit": "나가기",
		"notSubscriber": "해당 스트리머를 구독하지 않았습니다.\r\n구독하시겠습니까?",
		"unknownError": "Unknown Error",
		"setIntervalRange": "구간 설정 중...",
		"addedQueue": "대기열에 추가했습니다.",
		"resetSetting": "초기화",
		"realResetSetting": "정말 설정을 초기화 하시겠습니까?\r\n프로그램이 재시작 됩니다.",
		"vodTitle": "제목",
		"vodTime": "시간",
		"vodStatus": "상태",
		"intervalRangeSaved": "구간 설정 중...",
		"alreadyAdded": "이미 추가된 영상입니다.",
		"stoppedDownload": "진행이 취소되었습니다.",
		"stoppedNoStatus": "상태를 알 수 없습니다.",
		"canceled": "취소됨",
		"noFreeSpace": "남은 공간이 10% 미만입니다.",
		"errorHandleNoAlert": "에러 페이지가 비활성화 되었습니다."
	}`
)
